name: build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: |
         sudo snap install bibref
         sudo apt install python3 python3-pexpect python3-bs4
    - name: bibref-py
      run: |
        mkdir bibref-git
        cd bibref-git
        git clone https://github.com/kovzol/bibref
        cd ..
        ln -s bibref-git/bibref/py/bibref
    - name: generate-brst
      run: |
        ./generate-brst.py
    - name: bibref-check
      run: |
         sudo apt install flex bison libsword-dev libsword-common libreadline-dev libboost-dev
         cd bibref-git/bibref
         mkdir build
         cd build
         cmake ..
         make
         make install || true
         cd ..
         cd statements
         make
         cd tests
         ./runme ../../../../generated-brst
